name: ged-probing
channels:
  - defaults
  - huggingface
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.10.1
  - torchvision=0.11.2
  - cudatoolkit=10.2
  - transformers=4.11.3
  - scikit-learn
  - pandas
  - seaborn
  - ipykernel
  - autopep8